=== mhujer/xml-feeds-schemas/heureka.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:sch="http://purl.oclc.org/dsdl/schematron" targetNamespace="urn:x-hujer:feed:heureka"
  xmlns="urn:x-hujer:feed:heureka" xmlns:feed="urn:x-hujer:feed:heureka"
  elementFormDefault="qualified" xmlns:gen="urn:x-hujer:feed:generic">
  <xs:import namespace="urn:x-hujer:feed:generic" schemaLocation="generic.xsd"/>
  <xs:annotation>
    <xs:documentation>Schéma pro XML formát pro srovnávač heureka.cz. Více informací o formátu na
      http://sluzby.heureka.cz/napoveda/import/</xs:documentation>
  </xs:annotation>
  <xs:element name="SHOP">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="SHOPITEM" maxOccurs="unbounded">
          <xs:annotation>
            <xs:appinfo>
              <sch:ns uri="urn:x-hujer:feed:heureka" prefix="feed"/>
              <sch:pattern
                name="PRODUCT je nepovinný, pokud jsou uvedeny elementy PRODUCTNAME a PRODUCTNAMEEXT">
                <sch:rule context="feed:SHOPITEM">
                  <sch:report
                    test="(not(feed:PRODUCTNAME) or not(feed:PRODUCTNAMEEXT)) and not(feed:PRODUCT)"
                    >Není zadáno PRODUCT ani PRODUCTNAME a PRODUCTNAMEEXT</sch:report>
                </sch:rule>
              </sch:pattern>
              <sch:pattern name="PRICE_VAT je nepovinné, pokud jsou vyplněn PRICE a VAT">
                <sch:rule context="feed:SHOPITEM">
                  <sch:report test="(not(feed:PRICE) or not(feed:VAT)) and not(feed:PRICE_VAT)">Není
                    zadáno PRICE_VAT ani PRICE a VAT</sch:report>
                </sch:rule>
              </sch:pattern>
            </xs:appinfo>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="PRODUCT">
                <xs:annotation>
                  <xs:documentation> obsahuje název produktu, musí obsahovat, snažte se uvádět
                    přesné označení produktu, vč. produktového (modelového) čísla. Pokud názvy
                    produktů nebudou obsahovat produktové číslo, hrozí, že nedokážeme produkty
                    správně identifikovat a tudíž spárovat. Do názvu produktu neuvádějte žádné další
                    přívlastky, typu doprava zdarma, plus pouzdro, skladem aj.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minLength value="6"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="DESCRIPTION" type="xs:string">
                <xs:annotation>
                  <xs:documentation>popis produktu, snažte se uvádět co nejrelevantnější popis, ve
                    fulltextovém vyhledávání se bere v potaz</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="URL" type="xs:anyURI">
                <xs:annotation>
                  <xs:documentation>url adresa produktu, na této adrese musí být uvedena cena
                    produktu</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="IMGURL" type="xs:anyURI">
                <xs:annotation>
                  <xs:documentation>url adresa obrázku produktu</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="PRICE" minOccurs="0" type="TYPE_HEUREKA_PRICE">
                <xs:annotation>
                  <xs:documentation>cena produktu bez DPH, v ceně musí být uvedeny autorské a
                    recyklační poplatky pokud nejsou uvedeny zvlášť v položce
                    DUES</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="PRICE_VAT" minOccurs="0" type="TYPE_HEUREKA_PRICE">
                <xs:annotation>
                  <xs:documentation>cena produktu s DPH, v ceně musí být uvedeny autorské a
                    recyklační poplatky pokud nejsou uvedeny zvlášť v položce
                    DUES</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="DUES" type="TYPE_HEUREKA_PRICE" minOccurs="0"/>
              <xs:element name="VAT" minOccurs="0">
                <xs:simpleType>
                  <xs:union>
                    <xs:simpleType>
                      <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0"/>
                        <xs:maxExclusive value="2"/>
                      </xs:restriction>
                    </xs:simpleType>
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="(0|1),[0-9]{2}"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:union>
                </xs:simpleType>
              </xs:element>
              <xs:element name="ITEM_TYPE" minOccurs="0" type="gen:TYPE_ITEM_TYPE">
                <xs:annotation>
                  <xs:documentation>k rozlišení nových a bazarových položek. Nová položka: new
                    Bazarová (i repasovaná) položka: bazaar</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="MANUFACTURER" type="xs:string" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>obsahuje název výrobce produktu</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="CATEGORYTEXT" type="xs:string" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>zařazení produktu do kategorie, uvádějte vždy celou cestu k
                    produktu, tak jak to máte na Vašem eshopu (stačí nám tedy Vaše
                    kategorie)</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="EAN" type="gen:TYPE_EAN13_CODE" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>EAN kód je používán k označování jednotlivých druhů zboží.
                    Podporujeme formát EAN 13. Neuvádějte však interní čísla produktů, ale oficiální
                    kódy zboží!</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="ISBN" type="TYPE_HEUREKA_ISBN" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>je alfanumerický kód určený pro jednoznačnou identifikaci
                    knižních vydání. Podporujeme formáty ISBN-10 a ISBN-13. Čísla v ISBN kódu se
                    oddělují pomlčkou, například "978-0-123456-47-2"</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="DELIVERY_DATE" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Dodací doba zboží ve dnech</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                  <xs:restriction base="xs:int">
                    <xs:minInclusive value="0"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="PARAM" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>zde lze uvést další parametry produktu, pokud nejsou parametry
                    vyplněné, pak není možné zobrazovat Vaše produkty v konkrétním
                    filtrování</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="PARAM_NAME" type="xs:string"/>
                    <xs:element name="VAL" type="xs:string" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="url-je-ve-feedu-unikatni">
      <xs:annotation>
        <xs:documentation>URL produktu musí být v rámci feedu unikátní</xs:documentation>
      </xs:annotation>
      <xs:selector xpath="feed:SHOPITEM"/>
      <xs:field xpath="feed:URL"/>
    </xs:unique>
  </xs:element>

  <xs:simpleType name="TYPE_HEUREKA_PRICE">
    <xs:union>
      <xs:simpleType>
        <xs:restriction base="gen:TYPE_PRICE_POSITIVE">
          <xs:fractionDigits value="2"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="[0-9 ]{1,99}(,{0,1}[0-9]{1,2}){0,1}"/>
          <xs:pattern value=""/>
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>

  <xs:simpleType name="TYPE_HEUREKA_ISBN">
    <xs:restriction base="xs:string">
      <xs:minLength value="10"/>
      <xs:maxLength value="20"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== mhujer/xml-feeds-schemas/heureka.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="heureka-web.xsl"?>
<SHOP xmlns="urn:x-hujer:feed:heureka" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:x-hujer:feed:heureka heureka.xsd">
	<SHOPITEM>
		<PRODUCT>Nokia 5800 XpressMusic</PRODUCT>
		<DESCRIPTION>Klasický s plným dotykovým uživatelským rozhraním</DESCRIPTION>
		<URL>http://obchod.cz/mobily/nokia-5800-xpressmusic</URL>
		<IMGURL>http://obchod.cz/mobily/nokia-5800- xpressmusic/obrazek.jpg</IMGURL>
		<PRICE>5000</PRICE>
		<PRICE_VAT>6000</PRICE_VAT>
		<VAT>0,20</VAT>
		<ITEM_TYPE>new</ITEM_TYPE>
		<MANUFACTURER>NOKIA</MANUFACTURER>
		<CATEGORYTEXT>Elektronika | Mobilní telefony</CATEGORYTEXT>
		<EAN>6417182041488</EAN>
		<DELIVERY_DATE>2</DELIVERY_DATE>
	</SHOPITEM>
	<SHOPITEM>
		<PRODUCT>Nokia 5800 XpressMusic</PRODUCT>
		<DESCRIPTION>Klasický s plným dotykovým uživatelským rozhraním</DESCRIPTION>
		<URL>http://obchod.cz/mobily/nokia-5800-xpressmusic2</URL>
		<IMGURL>http://obchod.cz/mobily/nokia-5800- xpressmusic/obrazek.jpg</IMGURL>
		<PRICE>5 000,50</PRICE>
		<PRICE_VAT>6000</PRICE_VAT>
		<VAT>0,20</VAT>
	</SHOPITEM>
	<SHOPITEM>
		<PRODUCT>Nokia 5800 XpressMusic</PRODUCT>
		<DESCRIPTION>Klasický s plným dotykovým uživatelským rozhraním</DESCRIPTION>
		<URL>http://obchod.cz/mobily/nokia-5800-xpressmusic3</URL>
		<IMGURL>http://obchod.cz/mobily/nokia-5800- xpressmusic/obrazek.jpg</IMGURL>
		<PRICE>5 000,50</PRICE>
		<PRICE_VAT>6000</PRICE_VAT>
		<VAT>0,20</VAT>
	</SHOPITEM>

	<!-- Ukázka kvalitního XML souboru pro PARFÉMY -->
	<SHOPITEM>
		<PRODUCT>Hugo Boss No.6 toaletní voda 100 ml</PRODUCT>
		<DESCRIPTION>Úspěšný muž nové éry - cílevědomý, úspěšný se zdravou dávkou sebedůvěry. Výrazná mužná vůně...</DESCRIPTION>
		<URL>http://obchodxx.cz/parfemy/hugo-boss-no.6-toaletni-voda-100-ml/</URL>
		<IMGURL>http://obchodxx.cz/parfemy/hugo-boss-no.6-toaletni-voda-100-ml/321/obrazek.jpg</IMGURL>
		<PRICE_VAT>890</PRICE_VAT>
		<MANUFACTURER>Hugo Boss</MANUFACTURER>
		<CATEGORYTEXT>parfémy</CATEGORYTEXT>
		<EAN>7370523511000</EAN>
		<DELIVERY_DATE>2</DELIVERY_DATE>
		<PARAM>
			<PARAM_NAME>Určení</PARAM_NAME>
			<VAL>pánský</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Typ</PARAM_NAME>
			<VAL>toaletní voda</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Objem</PARAM_NAME>
			<VAL>100 ml</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Hlava parfému</PARAM_NAME>
			<VAL>jablko; sladká skořice; bergamot</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Srdce parfému</PARAM_NAME>
			<VAL>Geranium; hřebíček; mech</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Základ parfému</PARAM_NAME>
			<VAL>Cedrové dřevo; santalové dřevo; vetiver; olivové dřevo</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Tester</PARAM_NAME>
			<VAL>ne</VAL>
		</PARAM>
	</SHOPITEM>
	<SHOPITEM>
		<PRODUCT>DKNY Be Delicious parfémovaná voda 100 ml</PRODUCT>
		<DESCRIPTION>Dámská parfemová voda Žena, muž a jablko. To je nová vůně DKNY Be Delicious inspirovaná New Yorkem...</DESCRIPTION>
		<URL>http://obchodxx.cz/parfemy/dkny-be-delicious-parfemovana-voda-100-ml/</URL>
		<IMGURL>http://obchodxx.cz/parfemy/dkny-be-delicious-parfemovana-voda-100-ml/321/obrazek.jpg</IMGURL>
		<PRICE_VAT>1190</PRICE_VAT>
		<MANUFACTURER>DKNY</MANUFACTURER>
		<CATEGORYTEXT>parfémy|parfémovaná voda</CATEGORYTEXT>
		<EAN>7635110098240</EAN>
		<DELIVERY_DATE>2</DELIVERY_DATE>
		<PARAM>
			<PARAM_NAME>Určení</PARAM_NAME>
			<VAL>dámský</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Typ</PARAM_NAME>
			<VAL>parfémovaná voda</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Objem</PARAM_NAME>
			<VAL>100 ml</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Hlava parfému</PARAM_NAME>
			<VAL>zelené jablko; grapefruit; okurka; magnolie</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Srdce parfému</PARAM_NAME>
			<VAL>Tuberóza; růže; konvalinka; fialka</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Základ parfému</PARAM_NAME>
			<VAL>světlé dřevo; santalové dřevo; exotické květiny; bílá ambra</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Tester</PARAM_NAME>
			<VAL>ne</VAL>
		</PARAM>
	</SHOPITEM>

	<SHOPITEM>
		<PRODUCT>Bvlgari pour Homme toaletní voda 100 ml Tester</PRODUCT>
		<DESCRIPTION>Bvlgari Pour Homme EDT 100ml M TESTER Toaletní voda pro muže...</DESCRIPTION>
		<URL>http://obchodxx.cz/parfemy/bvlgari-pour-homme-toaletni-voda-100-ml-tester/</URL>
		<IMGURL>http://obchodxx.cz/parfemy/bvlgari-pour-homme-toaletni-voda-100-ml-tester/321/obrazek.jpg</IMGURL>
		<PRICE_VAT>536</PRICE_VAT>
		<MANUFACTURER>Bvlgari</MANUFACTURER>
		<CATEGORYTEXT>parfémy | toaletni vody</CATEGORYTEXT>
		<EAN>8591110000100</EAN>
		<DELIVERY_DATE>2</DELIVERY_DATE>
		<PARAM>
			<PARAM_NAME>Určení</PARAM_NAME>
			<VAL>pánský</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Typ</PARAM_NAME>
			<VAL>toaletní voda</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Objem</PARAM_NAME>
			<VAL>100 ml</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Hlava parfému</PARAM_NAME>
			<VAL>bergamot; levandule; mandarinka; aldehyd</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Srdce parfému</PARAM_NAME>
			<VAL>čaj darjeeling; pepř; koriandr; muškát; karafiát</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Základ parfému</PARAM_NAME>
			<VAL>Cedrové dřevo; jantar; fazole tonka; dubový mech</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Tester</PARAM_NAME>
			<VAL>ano</VAL>
		</PARAM>
	</SHOPITEM>

	<!-- Ukázka kvalitního XML souboru pro KNIHY -->
	<SHOPITEM>
		<PRODUCT>Tajemství – Jacqueline Wilsonová</PRODUCT>
		<DESCRIPTION>Příběh o přátelství Zlaty a Indie, o dívkách ze sociálně rozdílných rodin. Knížka pro děti okolo deseti let.</DESCRIPTION>
		<URL>http://obchodxx.cz/knihy/122655/Tajemstvi/</URL>
		<IMGURL>http://obchodxx.cz/knihy/122655/Tajemstvi//obrazek.jpg</IMGURL>
		<PRICE_VAT>134</PRICE_VAT>
		<ITEM_TYPE>bazaar</ITEM_TYPE>
		<MANUFACTURER>BB art</MANUFACTURER>
		<CATEGORYTEXT>Knihy | beletrie</CATEGORYTEXT>
		<EAN>9788072579525</EAN>
		<ISBN>80-7257-952-5</ISBN>
		<DELIVERY_DATE>2</DELIVERY_DATE>
		<PARAM>
			<PARAM_NAME>Žánr</PARAM_NAME>
			<VAL>dětská</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Vazba</PARAM_NAME>
			<VAL>vázaná</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Autor</PARAM_NAME>
			<VAL>Jacqueline Wilsonová</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Jazyk</PARAM_NAME>
			<VAL>Česky</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Počet stran</PARAM_NAME>
			<VAL>186</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Rok vydání</PARAM_NAME>
			<VAL>2004</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Nakladatelství</PARAM_NAME>
			<VAL>BB art</VAL>
		</PARAM>
	</SHOPITEM>
	<SHOPITEM>
		<PRODUCT>Tajemství – Danielle Steelová</PRODUCT>
		<DESCRIPTION>beletrie ostatní</DESCRIPTION>
		<URL>http://obchod.cz/knihy/122655/Tajemstvi-Steel/</URL>
		<IMGURL>http://obchod.cz/knihy/122655/Tajemstvi-Steel/obrazek.jpg</IMGURL>
		<PRICE_VAT>67</PRICE_VAT>
		<MANUFACTURER>Ikar</MANUFACTURER>
		<CATEGORYTEXT>Knihy | beletrie</CATEGORYTEXT>
		<EAN>8063859741252</EAN>
		<ISBN>80-6385-974-1</ISBN>
		<DELIVERY_DATE>2</DELIVERY_DATE>
		<PARAM>
			<PARAM_NAME>Žánr</PARAM_NAME>
			<VAL>beletrie</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Vazba</PARAM_NAME>
			<VAL>vázaná</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Autor</PARAM_NAME>
			<VAL>Danielle Steel</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Jazyk</PARAM_NAME>
			<VAL>Česky</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Počet stran</PARAM_NAME>
			<VAL>237</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Rok vydání</PARAM_NAME>
			<VAL>1996</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Nakladatelství</PARAM_NAME>
			<VAL>Ikar</VAL>
		</PARAM>
	</SHOPITEM>

	<SHOPITEM>
		<PRODUCT>Tajemství – Julie Garwood</PRODUCT>
		<DESCRIPTION>Judith Hamptonová, krásná a zároveň cílevědomá anglická dívka, slíbila své skotské přítelkyni z dětství, že jí bude stát po boku, až nastane čas narození jejího dítěte. Ale důvodem Judithina putování na vzdálenou skotskou Vysočinu je ještě něco jiného - touha shledat se s otcem, kterého nikdy nepoznala a o jehož existenci se dověděla teprve nedávno</DESCRIPTION>
		<URL>http://obchod.cz/knihy/122655/Tajemstvi-Garwood/</URL>
		<IMGURL>http://obchod.cz/knihy/122655/Tajemstvi-Garwood/obrazek.jpg</IMGURL>
		<PRICE_VAT>109</PRICE_VAT>
		<MANUFACTURER>OLDAG</MANUFACTURER>
		<CATEGORYTEXT>Knihy | beletrie</CATEGORYTEXT>
		<EAN>8054698231795</EAN>
		<ISBN>80-5469-823-1</ISBN>
		<DELIVERY_DATE>2</DELIVERY_DATE>
		<PARAM>
			<PARAM_NAME>Žánr</PARAM_NAME>
			<VAL>beletrie</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Vazba</PARAM_NAME>
			<VAL>pevná</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Autor</PARAM_NAME>
			<VAL>Julie Garwood</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Jazyk</PARAM_NAME>
			<VAL>Česky</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Počet stran</PARAM_NAME>
			<VAL>328</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Rok vydání</PARAM_NAME>
			<VAL>2007</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Nakladatelství</PARAM_NAME>
			<VAL>OLDAG</VAL>
		</PARAM>
	</SHOPITEM>

	<!-- Ukázka kvalitního XML souboru pro PNEUMATIKY  -->
	<SHOPITEM>
		<PRODUCT>Barum Polaris 2 165/70 R13 79T</PRODUCT>
		<DESCRIPTION>Zimní pneumatiky Barum Polaris 2 165/70 R13 79 T . Nová zimní pneumatika Polaris 2 je nástupcem...</DESCRIPTION>
		<URL>http://obchodxx.cz/pneumatiky/barum-polaris-2-165/70-r13-79t/</URL>
		<IMGURL>http://obchodxx.cz/pneumatiky/barum-polaris-2-165/70-r13-79t/obrazek.jpg</IMGURL>
		<PRICE_VAT>664</PRICE_VAT>
		<MANUFACTURER>Barum</MANUFACTURER>
		<CATEGORYTEXT>pneumatiky|zimni</CATEGORYTEXT>
		<EAN>4024063261297</EAN>
		<DELIVERY_DATE>2</DELIVERY_DATE>
		<PARAM>
			<PARAM_NAME>Období</PARAM_NAME>
			<VAL>zimní</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Zatížení</PARAM_NAME>
			<VAL>osobní</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Nominální šířka</PARAM_NAME>
			<VAL>165</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Vnitřní průměr</PARAM_NAME>
			<VAL>R13</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Index rychlosti</PARAM_NAME>
			<VAL>T (190km/h)</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Profil</PARAM_NAME>
			<VAL>70</VAL>
		</PARAM>
		<PARAM>
			<PARAM_NAME>Index nosnosti</PARAM_NAME>
