=== mhujer/xml-feeds-schemas/jyxo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:sch="http://purl.oclc.org/dsdl/schematron" targetNamespace="urn:x-hujer:feed:jyxo"
  xmlns="urn:x-hujer:feed:jyxo" xmlns:feed="urn:x-hujer:feed:jyxo" elementFormDefault="qualified"
  xmlns:gen="urn:x-hujer:feed:generic">
  <xs:import namespace="urn:x-hujer:feed:generic" schemaLocation="generic.xsd"/>
  <xs:element name="SHOP">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="SHOPITEM" maxOccurs="unbounded">
          <xs:annotation>
            <xs:appinfo>
              <sch:ns uri="urn:x-hujer:feed:jyxo" prefix="feed"/>
              <sch:pattern name="PRICE_VAT je nepovinné, pokud jsou vyplněn PRICE a VAT">
                <sch:rule context="feed:SHOPITEM">
                  <sch:report test="(not(feed:PRICE) or not(feed:VAT)) and not(feed:PRICE_VAT)">Není
                    zadáno PRICE_VAT ani PRICE a VAT</sch:report>
                </sch:rule>
              </sch:pattern>
            </xs:appinfo>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="PRODUCT" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Stručný název výrobku či služby (délky nejlépe do 64
                    znaků).</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="DESCRIPTION">
                <xs:annotation>
                  <xs:documentation>popis výrobku či služby (délka maximálně 1024 znaků, bez HTML
                    značek, HTML entit a formátování)</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="1024"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="URL" type="xs:anyURI">
                <xs:annotation>
                  <xs:documentation>Odkaz na stránku s nabídkou daného výrobku či služby (unikátní v
                    rámci feedu, tj. každé zboží má URL odlišné od URL ostatního
                    zboží).</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="IMGURL" type="xs:anyURI" minOccurs="0"/>
              <xs:element name="PRICE" minOccurs="0" type="gen:TYPE_PRICE_POSITIVE"/>
              <xs:element name="PRICE_VAT" minOccurs="0" type="gen:TYPE_PRICE_POSITIVE"/>
              <xs:element name="VAT" minOccurs="0">
                <xs:simpleType>
                  <xs:union>
                    <xs:simpleType>
                      <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                      </xs:restriction>
                    </xs:simpleType>
                    <xs:simpleType>
                      <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:union>
                </xs:simpleType>
              </xs:element>
              <xs:element name="MANUFACTURER" type="xs:string" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Jméno výrobce produktu.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="EAN" type="gen:TYPE_EAN13_CODE" minOccurs="0"/>
              <xs:element name="DELIVERY_DATE" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Dodací doba zboží ve dnech</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                  <xs:union>
                    <xs:simpleType>
                      <xs:restriction base="xs:date"/>
                    </xs:simpleType>
                    <xs:simpleType>
                      <xs:restriction base="xs:int">
                        <xs:minInclusive value="0"/>
                      </xs:restriction>
                    </xs:simpleType>
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="ihned"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:union>
                </xs:simpleType>
              </xs:element>
              <xs:element name="ITEM_TYPE" minOccurs="0" type="gen:TYPE_ITEM_TYPE">
                <xs:annotation>
                  <xs:documentation>Pokud je daná položka bazarová, uveďte jako hodnotu bazaar.
                    Jinak můžete tuto položku vypustit.</xs:documentation>
                </xs:annotation>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="url-je-ve-feedu-unikatni">
      <xs:annotation>
        <xs:documentation>URL produktu musí být v rámci feedu unikátní</xs:documentation>
      </xs:annotation>
      <xs:selector xpath="feed:SHOPITEM"/>
      <xs:field xpath="feed:URL"/>
    </xs:unique>
  </xs:element>
</xs:schema>

=== mhujer/xml-feeds-schemas/jyxo.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="jyxo-web.xsl"?>
<SHOP xmlns="urn:x-hujer:feed:jyxo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:x-hujer:feed:jyxo jyxo.xsd">
	<SHOPITEM>
		<PRODUCT>Podložka pod myš - kočka</PRODUCT>
		<DESCRIPTION>Ergonomická podložka pod myš, potisk s perskou kočkou.</DESCRIPTION>
		<URL>http://obchod.cz/podlozky-pod-mys/kocka</URL>
		<IMGURL>http://obchod.cz/obrazky/podlozky-pod-mys/kocka.jpg</IMGURL>
		<PRICE>420</PRICE>
		<PRICE_VAT>504</PRICE_VAT>
		<VAT>0.2</VAT>
		<MANUFACTURER>Genius</MANUFACTURER>
		<EAN>8594026341404</EAN>
		<DELIVERY_DATE>14</DELIVERY_DATE>
	</SHOPITEM>
	<SHOPITEM>
		<PRODUCT>Světélkující podložka pod myš</PRODUCT>
		<DESCRIPTION>Fosforeskující okraj, nevyžaduje baterie.</DESCRIPTION>
		<URL>http://obchod.cz/podlozky-pod-mys/fosfor</URL>
		<IMGURL>http://obchod.cz/obrazky/podlozky-pod-mys/fosfor.jpg</IMGURL>
		<PRICE>620</PRICE>
		<PRICE_VAT>744</PRICE_VAT>
		<ITEM_TYPE>bazaar</ITEM_TYPE>
	</SHOPITEM>
</SHOP>
