=== mhujer/xml-feeds-schemas/zbozi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:sch="http://purl.oclc.org/dsdl/schematron" targetNamespace="urn:x-hujer:feed:zbozi"
  xmlns="urn:x-hujer:feed:zbozi" elementFormDefault="qualified">
  <xs:element name="SHOP">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="SHOPITEM" maxOccurs="unbounded">
          <xs:annotation>
            <xs:appinfo>
              <sch:ns uri="urn:x-hujer:feed:zbozi" prefix="feed"/>
              <sch:pattern
                name="PRODUCT je nepovinný, pokud jsou uvedeny elementy PRODUCTNAME a PRODUCTNAMEEXT">
                <sch:rule context="feed:SHOPITEM">
                  <sch:report
                    test="(not(feed:PRODUCTNAME) or not(feed:PRODUCTNAMEEXT)) and not(feed:PRODUCT)"
                    >Není zadáno PRODUCT ani PRODUCTNAME a PRODUCTNAMEEXT</sch:report>
                </sch:rule>
              </sch:pattern>
              <sch:pattern name="PRICE_VAT je nepovinné, pokud jsou vyplněn PRICE a VAT">
                <sch:rule context="feed:SHOPITEM">
                  <sch:report test="(not(feed:PRICE) or not(feed:VAT)) and not(feed:PRICE_VAT)">Není
                    zadáno PRICE_VAT ani PRICE a VAT</sch:report>
                </sch:rule>
              </sch:pattern>
            </xs:appinfo>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="PRODUCT" type="xs:string" minOccurs="0"/>
              <xs:element name="PRODUCTNAME" type="xs:string" minOccurs="0"/>
              <xs:element name="PRODUCTNAMEEXT" type="xs:string" minOccurs="0"/>
              <xs:element name="DESCRIPTION" type="xs:string"/>
              <xs:element name="URL" type="xs:anyURI"/>
              <xs:element name="ITEM_TYPE">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="new"/>
                    <xs:enumeration value="bazaar"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="DELIVERY_DATE">
                <xs:simpleType>
                  <xs:union>
                    <xs:simpleType>
                      <xs:restriction base="xs:date"/>
                    </xs:simpleType>
                    <xs:simpleType>
                      <xs:restriction base="xs:int">
                        <xs:minInclusive value="0"/>
                      </xs:restriction>
                    </xs:simpleType>
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="ihned"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:union>
                </xs:simpleType>
              </xs:element>
              <xs:element name="IMGURL" type="xs:anyURI" minOccurs="0"/>
              <!-- @todo check PRICE/PRICE_VAT/VAT with Schematron! -->
              <xs:element name="PRICE" minOccurs="0" type="TYPE_PRICE_POSITIVE"/>
              <xs:element name="PRICE_VAT" minOccurs="0" type="TYPE_PRICE_POSITIVE"/>
              <xs:element name="VAT" minOccurs="0">
                <xs:simpleType>
                  <xs:union>
                    <xs:simpleType>
                      <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                      </xs:restriction>
                    </xs:simpleType>
                    <xs:simpleType>
                      <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:union>
                </xs:simpleType>
              </xs:element>
              <xs:element name="DUES" type="TYPE_PRICE" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="TYPE_PRICE">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TYPE_PRICE_POSITIVE">
    <xs:restriction base="xs:decimal">
      <xs:minExclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== mhujer/xml-feeds-schemas/zbozi.xml
<?xml version="1.0" encoding="UTF-8"?>
<SHOP xmlns="urn:x-hujer:feed:zbozi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:x-hujer:feed:zbozi zbozi.xsd">
    <SHOPITEM>
        <PRODUCT>Světélkující podložka pod myš</PRODUCT>
        <DESCRIPTION>Fosforeskující okraj, nevyžaduje baterie.</DESCRIPTION>
        <URL>http://obchod.cz/podlozky-pod-mys/fosfor</URL>
        <ITEM_TYPE>new</ITEM_TYPE>
        <DELIVERY_DATE>0</DELIVERY_DATE>
        <IMGURL>http://obchod.cz/obrazky/podlozky-pod-mys/fosfor.jpg</IMGURL>
        <PRICE>620</PRICE>
        <VAT>20</VAT>
    </SHOPITEM>
    <SHOPITEM>
        <PRODUCT>Světélkující podložka pod myš</PRODUCT>
        <DESCRIPTION>Fosforeskující okraj, nevyžaduje baterie.</DESCRIPTION>
        <URL>http://obchod.cz/podlozky-pod-mys/fosfor</URL>
        <ITEM_TYPE>new</ITEM_TYPE>
        <DELIVERY_DATE>0</DELIVERY_DATE>
        <IMGURL>http://obchod.cz/obrazky/podlozky-pod-mys/fosfor.jpg</IMGURL>
        <PRICE>620</PRICE>
        <VAT>0.2</VAT>
    </SHOPITEM>
    <SHOPITEM>
        <PRODUCT>Světélkující podložka pod myš</PRODUCT>
        <DESCRIPTION>Fosforeskující okraj, nevyžaduje baterie.</DESCRIPTION>
        <URL>http://obchod.cz/podlozky-pod-mys/fosfor</URL>
        <ITEM_TYPE>new</ITEM_TYPE>
        <DELIVERY_DATE>1</DELIVERY_DATE>
        <IMGURL>http://obchod.cz/obrazky/podlozky-pod-mys/fosfor.jpg</IMGURL>
        <PRICE_VAT>756</PRICE_VAT>
    </SHOPITEM>
    <SHOPITEM>
        <PRODUCT>Světélkující podložka pod myš</PRODUCT>
        <DESCRIPTION>Fosforeskující okraj, nevyžaduje baterie.</DESCRIPTION>
        <URL>http://obchod.cz/podlozky-pod-mys/fosfor</URL>
        <ITEM_TYPE>new</ITEM_TYPE>
        <DELIVERY_DATE>ihned</DELIVERY_DATE>
        <IMGURL>http://obchod.cz/obrazky/podlozky-pod-mys/fosfor.jpg</IMGURL>
        <PRICE>620</PRICE>
        <PRICE_VAT>756</PRICE_VAT>
        <VAT>0</VAT>
    </SHOPITEM>
    <!--<SHOPITEM>
        <PRODUCTNAME>Světélkující podložka pod myš</PRODUCTNAME>
        <DESCRIPTION>Fosforeskující okraj, nevyžaduje baterie.</DESCRIPTION>
        <URL>http://obchod.cz/podlozky-pod-mys/fosfor</URL>
        <ITEM_TYPE>new</ITEM_TYPE>
        <DELIVERY_DATE>2011-11-11</DELIVERY_DATE>
        <IMGURL>http://obchod.cz/obrazky/podlozky-pod-mys/fosfor.jpg</IMGURL>
        <PRICE>620</PRICE>
    </SHOPITEM>-->
    <SHOPITEM>
        <PRODUCTNAME>Světélkující podložka pod myš</PRODUCTNAME>
        <PRODUCTNAMEEXT>EXT</PRODUCTNAMEEXT>
        <DESCRIPTION>Fosforeskující okraj, nevyžaduje baterie.</DESCRIPTION>
        <URL>http://obchod.cz/podlozky-pod-mys/fosfor</URL>
        <ITEM_TYPE>new</ITEM_TYPE>
        <DELIVERY_DATE>2011-11-11</DELIVERY_DATE>
        <IMGURL>http://obchod.cz/obrazky/podlozky-pod-mys/fosfor.jpg</IMGURL>
        <PRICE>620</PRICE>
        <PRICE_VAT>756</PRICE_VAT>
    </SHOPITEM>
</SHOP>
